version: 0.1
log:
  level: debug
  fields:
    service: registry
    environment: development
  hooks:
    - type: mail
      disabled: true
storage:
    ipfs: {}
http:
    addr: :5000
    secret: asecretforlocaldevelopment
